 [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main', 'algo-test']
  pathPrefix = "/en"
  customDomain = "https://idyllic-cassata-b3391f.netlify.app/"
  renderJavaScript = true