[build]
  command = "yarn build"
  publish = "dist/"

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main', 'final_design', 'algo-test']
  renderJavaScript = true
