 [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main', 'draft/jolly-neumann']
  renderJavaScript = true