backend:
  name: git-gateway
  repo: https://github.com/AltSolutions1/public-kb
  branch: final_design
  # branch: main # Branch to update (optional; defaults to master)
  
# local_backend: true

publish_mode: editorial_workflow

media_folder: "src/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads

i18n: 
  structure: multiple_folders
  locales: [en, ar]
  default_locale: en

collections:
  - name: "kb-ar" 
    label: "KB - AR" 
    folder: "src/pages/posts/ar" 
    create: true 
    slug: "{{slug}}" 
    editor:
      preview: true
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/BlogPostLayout.astro"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Cards","Add money","Send money","Payments","Withdraw money", "Emergencies", "Tweeq account","Profile","Suggestions"]
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "kb-en"
    label: "KB - EN"
    folder: "src/pages/posts/en" 
    create: true
    slug: "{{slug}}" 
    # slug: "{{category}}/{{slug}}" 
    editor:
      preview: true
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/BlogPostLayout.astro"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Cards","Add money","Send money","Payments","Withdraw money", "Emergencies", "Tweeq account","Profile","Suggestions"]
      - {label: "Body", name: "body", widget: "markdown"}
 
  - name: "faq"
    label: "FAQ"
    folder: "src/pages/faqs"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    i18n: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/BlogPostLayout.astro",i18n: true }
      # - {label: "ID", name: "id", widget: "ncw-id", prefix: "faqs",i18n: duplicate } #this is widget not working--- will generate faqs-124hfkjas # timestamp: true     # will generate 1245119112-post-124hfkjas hint: This widget generate an unique read-only id
      - {label: "Title", name: "title", widget: "string",i18n: true}
      - {label: "Slug", name: "slug", widget: "string",i18n: true}
      - {label: "Body", name: "body", widget: "markdown",i18n: true}
  
      
