backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads

i18n: 
  structure: multiple_folders
  locales: [en, ar]
  default_locale: en

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: true
    i18n: true
    # editor:
    #   preview: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string",i18n: true}
      - {label: "Slug", name: "slug", widget: "string",i18n: duplicate}
      - {label: "Excerpt", name: "excerpt", widget: "string",i18n: true}
      - {label: "Publish Date", name: "date", widget: "datetime",i18n: duplicate,}
      - {label: "Author", name: "author", widget: "string",i18n: true}
      - label: "Category"
        name: "category"
        widget: "select"
        i18n: duplicate
        options: ["Cards", "Payments", "General", "Other"]
      - {label: "Body", name: "body", widget: "markdown",i18n: true}
